  version: "3.9"
  services:
    postgres:
      container_name: nestorPostgresSQLDB
      image: postgres
      environment:
        POSTGRES_DB: "nestor_db"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "admin"
      ports:
        - "5433:5432"